export const actionTypes = {

    ADD_MONEY: 'ADD_MONEY',
    ADD_EXPENSE: 'ADD_EXPENSE',

    ADD_USER: "ADD_USER",

    LOGOUT_USER: "LOGOUT_USER",
    LOGIN_USER: "LOGIN_USER",
    
    TRANSFER_MONEY: "TRANSFER_MONEY",
    ADD_ACTIVITY: "ADD_ACTIVITY"  
};
